# Generated by Django 5.2.17 on 2026-08-22 09:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('passed', 'Passed'), ('needs_review', 'Needs review')], default='not_started', max_length=20)),
                ('first_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='student_progress_entries', to='curriculum.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lesson_progress_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lesson_progress',
                'constraints': [models.UniqueConstraint(fields=('student', 'lesson'), name='lesson_progress_unique_student_lesson'), models.CheckConstraint(condition=models.Q(('status__in', ['not_started', 'in_progress', 'passed', 'needs_review'])), name='lesson_progress_status_valid'), models.CheckConstraint(condition=models.Q(('first_started_at__isnull', True), ('last_activity_at__isnull', True), ('last_activity_at__gte', models.F('first_started_at')), _connector='OR'), name='lesson_progress_activity_after_start')],
            },
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('posttest_taken', 'Posttest taken')], default='not_started', max_length=20)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('current_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='current_students', to='curriculum.lesson')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_progress',
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['not_started', 'in_progress', 'completed', 'posttest_taken'])), name='student_progress_status_valid')],
            },
        ),
    ]
