# Generated by Django 5.2.17 on 2026-08-22 09:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('pretest', 'Pretest'), ('posttest', 'Posttest')], max_length=10, unique=True)),
                ('time_limit_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assessment_config',
                'constraints': [models.CheckConstraint(condition=models.Q(('type__in', ['pretest', 'posttest'])), name='assessment_config_type_valid'), models.CheckConstraint(condition=models.Q(('time_limit_seconds__isnull', True), ('time_limit_seconds__gt', 0), _connector='OR'), name='assessment_config_time_positive')],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('pretest', 'Pretest'), ('posttest', 'Posttest')], max_length=10)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_questions', models.PositiveIntegerField()),
                ('time_limit_seconds', models.PositiveIntegerField()),
                ('admin_override', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assessment_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assessment_sessions',
            },
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_answer_index', models.PositiveSmallIntegerField()),
                ('is_correct', models.BooleanField()),
                ('assessment_question', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='responses', to='curriculum.assessmentquestion')),
                ('assessment_session', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='responses', to='assessment.assessmentsession')),
            ],
            options={
                'db_table': 'assessment_responses',
            },
        ),
        migrations.AddConstraint(
            model_name='assessmentsession',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['pretest', 'posttest'])), name='assessment_sessions_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='assessmentsession',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 100)), name='assessment_sessions_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='assessmentsession',
            constraint=models.CheckConstraint(condition=models.Q(('total_questions__gt', 0)), name='assessment_sessions_questions_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmentsession',
            constraint=models.CheckConstraint(condition=models.Q(('time_limit_seconds__gt', 0)), name='assessment_sessions_time_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmentsession',
            constraint=models.CheckConstraint(condition=models.Q(('completed_at__isnull', True), ('completed_at__gte', models.F('started_at')), _connector='OR'), name='assessment_sessions_completed_after_start'),
        ),
        migrations.AddConstraint(
            model_name='assessmentresponse',
            constraint=models.CheckConstraint(condition=models.Q(('selected_answer_index__range', (0, 3))), name='assessment_response_answer_index_0_3'),
        ),
        migrations.AddConstraint(
            model_name='assessmentresponse',
            constraint=models.UniqueConstraint(fields=('assessment_session', 'assessment_question'), name='assessment_response_unique_question'),
        ),
    ]
