# Generated by Django 5.2.17 on 2026-08-22 09:40

import accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='password_hash', max_length=255, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=10)),
                ('password_must_change', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'constraints': [models.CheckConstraint(condition=models.Q(('role__in', ['admin', 'teacher', 'student'])), name='users_role_valid'), models.CheckConstraint(condition=models.Q(models.Q(('deleted_at__isnull', True), ('is_active', True)), ('is_active', False), _connector='OR'), name='users_active_not_deleted')],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.UUIDField()),
                ('details_jsonb', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='teaching_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='ClassStudent',
            fields=[
                ('pk', models.CompositePrimaryKey('classroom', 'student', blank=True, editable=False, primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.RESTRICT, related_name='enrollments', to='accounts.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='class_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'class_students',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('session_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('login_at', models.DateTimeField()),
                ('last_heartbeat_at', models.DateTimeField()),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
                ('active_duration_seconds', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tracked_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_sessions',
            },
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deleted_at__isnull', True), ('is_active', True)), ('is_active', False), _connector='OR'), name='classes_active_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='usersession',
            constraint=models.CheckConstraint(condition=models.Q(('active_duration_seconds__gte', 0)), name='user_sessions_duration_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='usersession',
            constraint=models.CheckConstraint(condition=models.Q(('logout_at__isnull', True), ('logout_at__gte', models.F('login_at')), _connector='OR'), name='user_sessions_logout_after_login'),
        ),
        migrations.AddConstraint(
            model_name='usersession',
            constraint=models.CheckConstraint(condition=models.Q(('last_heartbeat_at__gte', models.F('login_at'))), name='user_sessions_heartbeat_after_login'),
        ),
    ]
