# Generated by Django 5.2.17 on 2026-08-22 09:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_questions', models.PositiveIntegerField()),
                ('study_time_seconds', models.PositiveIntegerField()),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sessions', to='curriculum.activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='activity_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_sessions',
            },
        ),
        migrations.CreateModel(
            name='ActivityResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_answer_index', models.PositiveSmallIntegerField()),
                ('is_correct', models.BooleanField()),
                ('video_checkpoint_reached', models.BooleanField(blank=True, null=True)),
                ('activity_question', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='responses', to='curriculum.activityquestion')),
                ('activity_session', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='responses', to='practice.activitysession')),
            ],
            options={
                'db_table': 'activity_responses',
            },
        ),
        migrations.CreateModel(
            name='ExerciseSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_questions', models.PositiveIntegerField()),
                ('study_time_seconds', models.PositiveIntegerField()),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exercise_sessions', to='curriculum.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exercise_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exercise_sessions',
            },
        ),
        migrations.CreateModel(
            name='ExerciseResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_answer_index', models.PositiveSmallIntegerField()),
                ('is_correct', models.BooleanField()),
                ('hint_used', models.BooleanField(default=False)),
                ('exercise_question', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='responses', to='curriculum.exercisequestion')),
                ('exercise_session', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='responses', to='practice.exercisesession')),
            ],
            options={
                'db_table': 'exercise_responses',
            },
        ),
        migrations.AddConstraint(
            model_name='activitysession',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 100)), name='activity_sessions_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='activitysession',
            constraint=models.CheckConstraint(condition=models.Q(('total_questions__gt', 0)), name='activity_sessions_questions_positive'),
        ),
        migrations.AddConstraint(
            model_name='activitysession',
            constraint=models.CheckConstraint(condition=models.Q(('study_time_seconds__gte', 0)), name='activity_sessions_study_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='activitysession',
            constraint=models.CheckConstraint(condition=models.Q(('completed_at__gte', models.F('started_at'))), name='activity_sessions_completed_after_start'),
        ),
        migrations.AddConstraint(
            model_name='activityresponse',
            constraint=models.CheckConstraint(condition=models.Q(('selected_answer_index__range', (0, 3))), name='activity_response_answer_index_0_3'),
        ),
        migrations.AddConstraint(
            model_name='activityresponse',
            constraint=models.UniqueConstraint(fields=('activity_session', 'activity_question'), name='activity_response_unique_question'),
        ),
        migrations.AddConstraint(
            model_name='exercisesession',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 100)), name='exercise_sessions_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='exercisesession',
            constraint=models.CheckConstraint(condition=models.Q(('total_questions__gt', 0)), name='exercise_sessions_questions_positive'),
        ),
        migrations.AddConstraint(
            model_name='exercisesession',
            constraint=models.CheckConstraint(condition=models.Q(('study_time_seconds__gte', 0)), name='exercise_sessions_study_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='exercisesession',
            constraint=models.CheckConstraint(condition=models.Q(('completed_at__gte', models.F('started_at'))), name='exercise_sessions_completed_after_start'),
        ),
        migrations.AddConstraint(
            model_name='exerciseresponse',
            constraint=models.CheckConstraint(condition=models.Q(('selected_answer_index__range', (0, 3))), name='exercise_response_answer_index_0_3'),
        ),
        migrations.AddConstraint(
            model_name='exerciseresponse',
            constraint=models.UniqueConstraint(fields=('exercise_session', 'exercise_question'), name='exercise_response_unique_question'),
        ),
    ]
