# Generated by Django 5.2.17 on 2026-08-22 09:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('practice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BKTModelParameters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('p_learn', models.DecimalField(decimal_places=4, max_digits=5)),
                ('p_slip', models.DecimalField(decimal_places=4, max_digits=5)),
                ('p_guess', models.DecimalField(decimal_places=4, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bkt_model_parameters',
                'constraints': [models.CheckConstraint(condition=models.Q(('p_learn__gte', 0), ('p_learn__lte', 1)), name='bkt_parameters_learn_0_1'), models.CheckConstraint(condition=models.Q(('p_slip__gte', 0), ('p_slip__lte', 1)), name='bkt_parameters_slip_0_1'), models.CheckConstraint(condition=models.Q(('p_guess__gte', 0), ('p_guess__lte', 1)), name='bkt_parameters_guess_0_1')],
            },
        ),
        migrations.CreateModel(
            name='ActivityQDecision',
            fields=[
                ('action', models.CharField(choices=[('advance', 'Advance'), ('review', 'Review'), ('retake', 'Retake')], max_length=10)),
                ('mastery_at_decision', models.DecimalField(decimal_places=4, max_digits=5)),
                ('study_time_seconds', models.PositiveIntegerField()),
                ('attempt_count', models.PositiveIntegerField()),
                ('session_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hint_count', models.PositiveIntegerField()),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_session', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='q_decision', to='practice.activitysession')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='activity_q_decisions', to='curriculum.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='activity_q_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_q_decisions',
                'constraints': [models.CheckConstraint(condition=models.Q(('action__in', ['advance', 'review', 'retake'])), name='activity_q_action_valid'), models.CheckConstraint(condition=models.Q(('mastery_at_decision__gte', 0), ('mastery_at_decision__lte', 1)), name='activity_q_mastery_0_1'), models.CheckConstraint(condition=models.Q(('study_time_seconds__gte', 0)), name='activity_q_study_nonnegative'), models.CheckConstraint(condition=models.Q(('attempt_count__gt', 0)), name='activity_q_attempt_positive'), models.CheckConstraint(condition=models.Q(('session_score__gte', 0), ('session_score__lte', 100)), name='activity_q_score_0_100'), models.CheckConstraint(condition=models.Q(('hint_count__gte', 0)), name='activity_q_hints_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='BKTMastery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('p_known', models.DecimalField(decimal_places=4, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mastery_estimates', to='curriculum.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mastery_estimates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bkt_mastery',
                'constraints': [models.UniqueConstraint(fields=('student', 'lesson'), name='bkt_mastery_unique_student_lesson'), models.CheckConstraint(condition=models.Q(('p_known__gte', 0), ('p_known__lte', 1)), name='bkt_mastery_known_0_1')],
            },
        ),
        migrations.CreateModel(
            name='ExerciseQDecision',
            fields=[
                ('action', models.CharField(choices=[('advance', 'Advance'), ('review', 'Review'), ('retake', 'Retake')], max_length=10)),
                ('mastery_at_decision', models.DecimalField(decimal_places=4, max_digits=5)),
                ('study_time_seconds', models.PositiveIntegerField()),
                ('attempt_count', models.PositiveIntegerField()),
                ('session_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hint_count', models.PositiveIntegerField()),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exercise_session', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='q_decision', to='practice.exercisesession')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exercise_q_decisions', to='curriculum.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exercise_q_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exercise_q_decisions',
                'constraints': [models.CheckConstraint(condition=models.Q(('action__in', ['advance', 'review', 'retake'])), name='exercise_q_action_valid'), models.CheckConstraint(condition=models.Q(('mastery_at_decision__gte', 0), ('mastery_at_decision__lte', 1)), name='exercise_q_mastery_0_1'), models.CheckConstraint(condition=models.Q(('study_time_seconds__gte', 0)), name='exercise_q_study_nonnegative'), models.CheckConstraint(condition=models.Q(('attempt_count__gt', 0)), name='exercise_q_attempt_positive'), models.CheckConstraint(condition=models.Q(('session_score__gte', 0), ('session_score__lte', 100)), name='exercise_q_score_0_100'), models.CheckConstraint(condition=models.Q(('hint_count__gte', 0)), name='exercise_q_hints_nonnegative')],
            },
        ),
    ]
