# Generated by Django 5.2.17 on 2026-08-22 09:40

import core.db_expressions
import core.validators
import django.db.models.deletion
import django.db.models.lookups
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order_index', models.PositiveIntegerField(unique=True)),
                ('content_jsonb', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prerequisite_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='dependent_lessons', to='curriculum.lesson')),
            ],
            options={
                'db_table': 'lessons',
            },
        ),
        migrations.CreateModel(
            name='ExerciseQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('options_jsonb', models.JSONField(validators=[core.validators.validate_four_options])),
                ('correct_answer_index', models.PositiveSmallIntegerField()),
                ('hint_text', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exercise_questions', to='curriculum.lesson')),
            ],
            options={
                'db_table': 'exercise_questions',
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('options_jsonb', models.JSONField(validators=[core.validators.validate_four_options])),
                ('correct_answer_index', models.PositiveSmallIntegerField()),
                ('has_image', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assessment_questions', to='curriculum.lesson')),
            ],
            options={
                'db_table': 'assessment_questions',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order_index', models.PositiveIntegerField(unique=True)),
                ('lesson_1', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='activities_as_first_lesson', to='curriculum.lesson')),
                ('lesson_2', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='activities_as_second_lesson', to='curriculum.lesson')),
            ],
            options={
                'db_table': 'activities',
            },
        ),
        migrations.CreateModel(
            name='ActivityQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('options_jsonb', models.JSONField(validators=[core.validators.validate_four_options])),
                ('correct_answer_index', models.PositiveSmallIntegerField()),
                ('media_jsonb', models.JSONField(blank=True, null=True)),
                ('order_index', models.PositiveIntegerField()),
                ('hint_text', models.TextField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='questions', to='curriculum.activity')),
            ],
            options={
                'db_table': 'activity_questions',
                'constraints': [models.CheckConstraint(condition=django.db.models.lookups.Exact(core.db_expressions.JsonArrayLength('options_jsonb'), 4), name='activity_options_exactly_four'), models.CheckConstraint(condition=models.Q(('correct_answer_index__range', (0, 3))), name='activity_answer_index_0_3'), models.CheckConstraint(condition=models.Q(('order_index__gte', 1)), name='activity_questions_order_positive'), models.UniqueConstraint(fields=('activity', 'order_index'), name='activity_questions_unique_order')],
            },
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(condition=models.Q(('order_index__gte', 1)), name='lessons_order_positive'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('prerequisite_lesson')), _negated=True), name='lessons_not_self_prerequisite'),
        ),
        migrations.AddConstraint(
            model_name='exercisequestion',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.Exact(core.db_expressions.JsonArrayLength('options_jsonb'), 4), name='exercise_options_exactly_four'),
        ),
        migrations.AddConstraint(
            model_name='exercisequestion',
            constraint=models.CheckConstraint(condition=models.Q(('correct_answer_index__range', (0, 3))), name='exercise_answer_index_0_3'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestion',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.Exact(core.db_expressions.JsonArrayLength('options_jsonb'), 4), name='assessment_options_exactly_four'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestion',
            constraint=models.CheckConstraint(condition=models.Q(('correct_answer_index__range', (0, 3))), name='assessment_answer_index_0_3'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestion',
            constraint=models.CheckConstraint(condition=models.Q(('has_image', False), ('image_url__isnull', False), _connector='OR'), name='assessment_image_url_when_needed'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('order_index__gte', 1)), name='activities_order_positive'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('lesson_1', models.F('lesson_2')), _negated=True), name='activities_lessons_distinct'),
        ),
    ]
